### ISSUE TITLE
NDIF images cannot be mounted via drag & drop

### ISSUE THREAD

**Issue by zxcvb3** [minivmac/minivmac#3]
I was trying to mount "MusicProse 2.1.img" and received the error: "The disk is damaged: Do you want to initialize it?"
After posting on a forum, a very knowledgeable user as able to identify the problem
> The particular disk image you have is a 'NDIF' format image, created by Disk Copy 6.x which only ran on System 7 and later. ('NDIF' stood for "new disk image format" and wasn't compatible with Disk Copy 4.2 on older systems.)

https://mega.nz/file/oHQXkJqD#8Ucl6kWShXDn5XKMrxsLtDbC6KL3ip6-cMYY5Wm6SsQ (extracted .img file)
https://www.macintoshrepository.org/408-musicprose-2-1 (.sit file that seems compatible with older version of stuffit)
https://macintoshgarden.org/apps/musicprose-21 (.sit file that seems compatible with older version of stuffit)
These should all result in the same .img, but I'm just posting all the links anyway.

Creating this issue at the request of Egon.

**Comment by egrath** [comment]
For reference, there are currently (37.03) two kind of supported disk images in Mini vMac:

1. Raw HFS images, used for floppy and harddisk images
2. DiskCopy 4.2 images, used for floppy. These use a 84 byte long header which contain various metadata and are simply stripped when inserted into a emulated floppy.

**The DiskCopy 6.3.3 situation**

Images generated with DiskCopy 6.3.3 are by default uncompressed raw hfs images of the filesystem on the physical floppy in the data fork and associated metadata in the resource fork. When copying such a image to a non Macintosh system, the resource fork is lost and only the raw hfs image survives. These images **are usable on Mini vMac** as of today.

What makes things complicated is that DiskCopy 6.3.3 also allows to compress the data fork (image becomes read-only). The fact that the data fork is compressed is stored in the resource fork.

**The complication and a eventual solution**

When deailing with a DiskCopy 6.3.3 compressed image file (speak, only the data fork), we don't know in the first place that it's compressed, as we don't have the resource fork. To make such images usable, we may have to:

1. Check if it's a HFS or DiskCopy 4.2 image
2. If it's not, try to uncompress it (with a yet unknown compression algorithm) into memory
3. If it's a valid HFS image after decompression, handle it over to the floppy emulation part for further processing

My next step is to (2) from the above list. Hopefully it's not something too proprietary.

**Comment by egrath** [comment]
After doing a little more research, i'm quite sure that this is a WONTFIX issue.

Problem is, that the data fork alone (the .img file) is not enough to recover the original data. Even Disk Copy 6.3.3 and hdiutil are not able to work with it, they both need the resource fork to handle it.
