### ISSUE TITLE
wayland support?

### ISSUE THREAD

**Issue by exoess** [minivmac/minivmac#7]
will you ever add wayland support for minivmac?

**Comment by egrath** [comment]
It already does :-)

Currently SDL is preferring X11 over Wayland, even when running on a Wayland session and is using Xwayland in that case [1]. However, you can force SDL to use Wayland by running minivmac like this:

```
SDL_VIDEODRIVER=wayland ./minivmac
```

For the reasons in [1], i won't apply the necessary hint to prefer Wayland.

[1] (https://github.com/libsdl-org/SDL/commit/254fcc90eb22bb159ab365ad956222a9c5632841)
